defaults: &defaults
  host: 127.0.0.1
  port: 27017
  adapter: mongodb

development:
  <<: *defaults
  database: harassforcash

test: 
  <<: *defaults
  database: harassforcash

production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
  database: harassforcash
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>